### ISSUE TITLE
Unit testing issue in "demo" caused due to csrf

### ISSUE THREAD

**Issue by shraddhayelamarthy** [afrasd/NITCONF#10]
As we have a new csrf code everytime we login it is difficult to make unit test cases for it

**Comment by shraddhayelamarthy** [comment]
fixed the issue

**Comment by siripagadala** [comment]
![WhatsApp Image 2024-01-23 at 14 48 26](https://github.com/afrasd/NITCONF/assets/103987545/f44ee831-d9c8-4ef0-bd89-403db08ba673)
