### ISSUE TITLE
query issue

### ISSUE THREAD

**Issue by siripagadala** [afrasd/NITCONF#11]
fetching only one attribute.

**Comment by siripagadala** [comment]
![E44860FD-5504-4F1D-AE95-2DEC8863A01D](https://github.com/afrasd/NITCONF/assets/103987545/5ed65b1f-1811-4657-a27e-fc26bc2480a3)

**Comment by shraddhayelamarthy** [comment]
Fixed it

**Comment by siripagadala** [comment]
![492CC1DE-A164-4349-9311-FE7CAECD52D8](https://github.com/afrasd/NITCONF/assets/103987545/b33ebd36-2dda-4b8d-b5e0-7c19b836c113)
