### ISSUE TITLE
bootstrap not reflecting in the toreview.html 

### ISSUE THREAD

**Issue by siripagadala** [afrasd/NITCONF#20]

**Comment by shraddhayelamarthy** [comment]
Fixed it by refreshing and project and clearing maven cache
<img width="953" alt="Screenshot 2024-01-30 134523" src="https://github.com/afrasd/NITCONF/assets/109479657/d06e406e-e303-40ef-9c62-6aea61aff6b9">

**Comment by shraddhayelamarthy** [comment]
<img width="959" alt="Screenshot 2024-01-30 141401" src="https://github.com/afrasd/NITCONF/assets/109479657/6923ea5e-33d7-476f-9c14-6638d76592b2">
