### ISSUE TITLE
Display all feature not working

### ISSUE THREAD

**Issue by afrasd** [afrasd/NITCONF#26]
Display all button in the review page is not displaying the reviews. It does not redirect to any page.

**Comment by shraddhayelamarthy** [comment]
<img width="950" alt="Screenshot 2024-02-06 085630" src="https://github.com/afrasd/NITCONF/assets/109479657/1e6b86f0-331c-47d3-b1d5-85d1002a1ec4">
It is now working after fixing the fetch query
